import type { Client } from './client';
import type { InvoiceCompany } from './invoice-company';

export interface InvoiceItem {
  id: string;
  user_id: string;
  invoice_id: string;
  description: string;
  quantity: number;
  unit_price: number;
  unit_price_usd?: number;
  unit_price_eur?: number;
  unit_price_aoa?: number;
  currency: string;
  exchange_rate_usd_to_eur?: number;
  exchange_rate_usd_to_aoa?: number;
  exchange_rate_eur_to_aoa?: number;
  tax_rate: number;
  tax_amount: number;
  tax_exemption_reason?: string;
  subtotal: number;
  total_with_tax: number;
  subtotal_usd?: number;
  subtotal_eur?: number;
  subtotal_aoa?: number;
  total_with_tax_usd?: number;
  total_with_tax_eur?: number;
  total_with_tax_aoa?: number;
  vat_number?: string;
  intra_community_supply: boolean;
  reverse_charge: boolean;
  angolan_tax_regime?: string;
  angolan_tax_exemption_code?: string;
  discount_percentage: number;
  discount_amount: number;
  item_reference?: string;
  item_category?: string;
  unit_of_measure: string;
  created_at: string;
  updated_at: string;
}

export interface Invoice {
  id: string;
  user_id: string;
  invoice_number: string;
  client_id: string;
  company_id: string;
  issue_date: string;
  due_date: string;
  currency: string;
  subtotal: number;
  tax_total: number;
  total: number;
  subtotal_usd?: number;
  tax_total_usd?: number;
  total_usd?: number;
  subtotal_eur?: number;
  tax_total_eur?: number;
  total_eur?: number;
  subtotal_aoa?: number;
  tax_total_aoa?: number;
  total_aoa?: number;
  exchange_rate_usd_to_eur?: number;
  exchange_rate_usd_to_aoa?: number;
  exchange_rate_eur_to_aoa?: number;
  status: string;
  notes?: string;
  language: string;
  created_at: string;
  updated_at: string;
  client: Client;
  company: InvoiceCompany;
  items: InvoiceItem[];
}